### ISSUE TITLE
Create a little template functionality

### ISSUE THREAD

**Issue by JacobNeergaard** [TRP-Solutions/heal-document#2]
<html>, <head>, <title>, and <body> are mandatory in a full HTML document.

Maybe make a constructor with HEAL_FULL_HTML param. A bit like the old Template.

Access via $html->body() and $html->head() afterwards.

$html->title();
$html->metadata();
$html->link();
$html->css();

manages head section.

**Comment by JacobNeergaard** [comment]
or
```
list($dom,$body,$head) = new HealHTML(HEAL_FULL_HTML);
```

**Comment by Zatnosk** [comment]
After discussion we landed on following solution:
```
$doc = new HealHTML();
list($head, $body) = $doc->html($title);
```
